### ISSUE TITLE
pygbq.update doesn't consider duplicated values

### ISSUE THREAD

**Issue by FedericoSala** [ZiggerZZ/pygbq#1]
I don't understand whether pygbq.update() considers duplicated records or not.
In my case, I have a table with 3 fields (field1 is the only required one in table's schema), pygbq.update() randomly creates some duplicated rows

Here's an example of the update I'm using:
`clientpygbq.update(data=df.to_dict('records'), table_id=f"{dataset}.{table}", how=['field1', 'field2','field3'],max_insert_num_rows=n, expiration=0.2)`

I was wondering to change field2/field3 as required, does you library consider the field mode while merging data?
Thanks in advance

**Comment by ZiggerZZ** [comment]
Hey @FedericoSala, can you please provide more information on your issue?
Examples of data in the table and what you're trying to insert.

**Comment by FedericoSala** [comment]
you can create a dataframe like this:
```
df = pd.DataFrame(columns=['date', 'bp_id','product_id'])
entry = pd.DataFrame.from_dict({
     "date": ["2022-05-20", "2022-05-20"],
     "bp_id":  ["ca1234", "ca1234"],
     "product_id": ["abc1", "abc1"]
})
df = pd.concat([df, entry], ignore_index=True)
```
In my table, the "date" field is the required one. After the update, I find both records in the table.

**Comment by ZiggerZZ** [comment]
If you have duplicated rows in the dataframe you're trying to merge into the existing table, they will end up being there. You need to deduplicate the rows in your Python code before uploading them into BigQuery.
I suggest you have a look at [drop_duplicates](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html) pandas function.
